Repository croct-tech/sdk-js, pull requests merged in 2020-06, with the labels that each got.

#84 Eliminate dependency on 3rd-party cookies
  src/cache/cookieCache.ts
  src/cache/fallbackCache.ts
  src/cache/inMemoryCache.ts
  src/cache/index.ts
  src/cache/storageCache.ts
  src/channel/beaconSocketChannel.ts
  src/cid/cachedAssigner.ts
  src/cid/fixedCidAssigner.ts
  src/cid/index.ts
  src/cid/remoteAssigner.ts
  src/container.ts
  src/cookie.ts
  src/evaluator.ts
  src/facade/sdkFacade.ts
  src/schema/sdkFacadeSchemas.ts
  src/schema/sdkSchemas.ts
  src/sdk.ts
  test/cache/cookieCache.test.ts
  test/cache/fallbackCache.test.ts
  test/cache/inMemoryCache.test.ts
  test/cache/storageCache.test.ts
  test/channel/beaconSocketChannel.test.ts
  test/cid/cachedCidAssigner.test.ts
  test/cid/fixedCidAssigner.test.ts
  test/cid/remoteCidAssigner.test.ts
  test/container.test.ts
  test/cookie.test.ts
  test/evaluator.test.ts
  test/facade/sdkFacade.test.ts
  test/schemas/sdkFacadeSchemas.test.ts
  test/schemas/sdkSchemas.test.ts
  test/sdk.test.ts
Labels: enhancement

#85 Move authentication tracking to SDK facade
  src/facade/sdkFacade.ts
  src/facade/userFacade.ts
  src/token/index.ts
  src/tracker.ts
  test/facade/sdkFacade.test.ts
  test/facade/userFacade.test.ts
  test/token/index.test.ts
  test/tracker.test.ts
Labels: enhancement

#86 Introduce an inter-service communication layer
  src/activeRecord.ts
  src/cache/cookieCache.ts
  src/cache/fallbackCache.ts
  src/cache/inMemoryCache.ts
  src/cache/index.ts
  src/cache/localStorageCache.ts
  src/cache/storageCache.ts
  src/container.ts
  src/context.ts
  src/evaluator.ts
  src/eventManager.ts
  src/facade/sdkFacade.ts
  src/facade/sessionPatch.ts
  src/facade/trackerFacade.ts
  src/facade/userPatch.ts
  src/sdk.ts
  src/sdkEvents.ts
  src/tab.ts
  src/token/cachedTokenStore.ts
  src/token/inMemoryTokenStore.ts
  src/token/index.ts
  src/token/persistentStorage.ts
  src/token/replicatedTokenStore.ts
  src/tracker.ts
  src/trackingEvents.ts
  test/cache/cookieCache.test.ts
  test/cache/fallbackCache.test.ts
  test/cache/inMemoryCache.test.ts
  test/cache/localStorageCache.test.ts
  test/cache/storageCache.test.ts
  test/channel/beaconSocketChannel.test.ts
  test/container.test.ts
  test/context.test.ts
  test/evaluator.test.ts
  test/eventManager.test.ts
  test/facade/sdkFacade.test.ts
  test/facade/sessionFacade.test.ts
  test/facade/sessionPatch.test.ts
  test/facade/trackerFacade.test.ts
  test/facade/userFacade.test.ts
  test/facade/userPatch.test.ts
  test/schemas/ecommerceSchemas.test.ts
  test/schemas/eventSchemas.test.ts
  test/sdk.test.ts
  test/token/cachedTokenStore.test.ts
  test/token/inMemoryStorage.test.ts
  test/token/index.test.ts
  test/token/persistentStorage.test.ts
  test/token/replicatedStorage.test.ts
  test/tracker.test.ts
  test/utils/tabEventEmulator.ts
Labels: breaking change, feature

#87 Cleanup SDK API
  src/eventManager.ts
  src/facade/sdkFacade.ts
  src/sdk.ts
  test/facade/sdkFacade.test.ts
  test/sdk.test.ts
Labels: breaking change, enhancement

#88 Change max length for custom key from 20 to 50 characters
  src/schema/userSchema.ts
  test/schemas/userSchema.test.ts
Labels: enhancement
