Repository croct-tech/sdk-js, pull requests merged in 2020-05, with the labels that each got.

#65 Fix release workflow
  .github/workflows/deploy-published-releases.yaml
Labels: maintenance

#66 Fix logo URL
  README.md
Labels: maintenance

#67 Update logo in readme
  README.md
Labels: maintenance

#68 Update badges in readme
  README.md
Labels: maintenance

#69 Add icons and direct links to readme's top menu
  README.md
Labels: maintenance

#70 Improve Github workflow
  .github/workflows/branch-validations.yaml
  package.json
Labels: maintenance

#71 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#72 Add support for object subtype validation
  src/validation/objectType.ts
  test/validation/objectType.test.ts
Labels: feature

#73 Add support for object subtype validation
  .github/workflows/branch-validations.yaml
  .github/workflows/deploy-published-releases.yaml
  .github/workflows/release-drafter.yaml
Labels: maintenance

#76 Add support for object type validation
  src/validation/objectType.ts
  test/validation/objectType.test.ts
Labels: feature

#77 Add support for function type validation
  .eslintrc.json
  src/validation/functionType.ts
  test/validation/functionType.test.ts
Labels: feature

#78 Add validation schema for loggers
  src/schema/loggerSchema.ts
  src/schema/sdkFacadeSchemas.ts
  src/schema/sdkSchemas.ts
  test/schemas/loggerSchema.test.ts
  test/schemas/sdkFacadeSchemas.test.ts
  test/schemas/sdkSchemas.test.ts
Labels: enhancement

#79 Allow loggers to have extra members
  src/schema/loggerSchema.ts
  test/schemas/loggerSchema.test.ts
Labels: enhancement

#80 Fix Github token
  .github/workflows/release-drafter.yaml
Labels: maintenance

#81 Export ES2015 modules to solve bundling issues with CommonJS
  tsconfig.json
Labels: enhancement

#82 Import Typescript runtime
  package-lock.json
  package.json
  tsconfig.json
Labels: maintenance
